[package]
name = "PyRapier2d"
version = "0.1.0"
edition = "2021"

[lib]
name = "PyRapier2d"
crate-type = ["cdylib"]

[dependencies]
rapier2d = "0.30.0" 
pyo3 = { version = "0.20.0", features = ["extension-module"] }